export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'

export const DELETE_ITEM = 'DELETE_ITEM'
export const ITEMS_LOADING = "ITEMS_LOADING"
export const INITIATE_USER = 'INITIATE_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const INVALID_LOGIN = 'INVALID_LOGIN'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'
